---
# Playbook: Linux Asset Inventory Collection
# Purpose: Thu thập thông tin asset inventory cho Linux systems
# Author: Security Team
# Usage: ansible-playbook -i inventory inventory_report.yml

- name: Linux Asset Inventory Collection
  hosts: all
  gather_facts: yes
  become: yes
  
  vars:
    report_dir: "/tmp/asset_inventory"
    report_date: "{{ ansible_date_time.date }}"
    
  tasks:
    # ============================================
    # SECTION 1: BASIC SYSTEM INFORMATION
    # ============================================
    - name: Create report directory
      file:
        path: "{{ report_dir }}"
        state: directory
        mode: '0755'
      delegate_to: localhost
      run_once: true
      become: no

    - name: Collect basic system info
      set_fact:
        system_info:
          hostname: "{{ ansible_hostname }}"
          fqdn: "{{ ansible_fqdn }}"
          domain: "{{ ansible_domain | default('N/A') }}"
          os_family: "{{ ansible_os_family }}"
          distribution: "{{ ansible_distribution }}"
          distribution_version: "{{ ansible_distribution_version }}"
          distribution_release: "{{ ansible_distribution_release | default('N/A') }}"
          kernel: "{{ ansible_kernel }}"
          architecture: "{{ ansible_architecture }}"
          machine_id: "{{ ansible_machine_id | default('N/A') }}"
          product_name: "{{ ansible_product_name | default('N/A') }}"
          product_serial: "{{ ansible_product_serial | default('N/A') }}"
          system_vendor: "{{ ansible_system_vendor | default('N/A') }}"
          virtualization_type: "{{ ansible_virtualization_type | default('physical') }}"
          virtualization_role: "{{ ansible_virtualization_role | default('N/A') }}"

    # ============================================
    # SECTION 2: HARDWARE INFORMATION
    # ============================================
    - name: Collect CPU information
      set_fact:
        cpu_info:
          processor: "{{ ansible_processor[2] | default(ansible_processor[1]) }}"
          processor_count: "{{ ansible_processor_count }}"
          processor_cores: "{{ ansible_processor_cores }}"
          processor_threads_per_core: "{{ ansible_processor_threads_per_core }}"
          processor_vcpus: "{{ ansible_processor_vcpus }}"

    - name: Collect memory information
      set_fact:
        memory_info:
          memtotal_mb: "{{ ansible_memtotal_mb }}"
          memfree_mb: "{{ ansible_memfree_mb }}"
          memory_used_mb: "{{ ansible_memtotal_mb | int - ansible_memfree_mb | int }}"
          memory_used_percent: "{{ ((ansible_memtotal_mb | int - ansible_memfree_mb | int) / ansible_memtotal_mb | int * 100) | round(2) }}"
          swaptotal_mb: "{{ ansible_swaptotal_mb }}"
          swapfree_mb: "{{ ansible_swapfree_mb }}"

    - name: Collect disk information
      set_fact:
        disk_info: "{{ ansible_mounts | map(attribute='mount') | list | zip(
                       ansible_mounts | map(attribute='device') | list,
                       ansible_mounts | map(attribute='fstype') | list,
                       ansible_mounts | map(attribute='size_total') | list,
                       ansible_mounts | map(attribute='size_available') | list) | list }}"

    - name: Calculate disk usage
      set_fact:
        disk_details: >-
          {%- set result = [] -%}
          {%- for mount in ansible_mounts -%}
            {%- set used = mount.size_total - mount.size_available -%}
            {%- set used_percent = (used / mount.size_total * 100) | round(2) if mount.size_total > 0 else 0 -%}
            {%- set _ = result.append({
              'mount': mount.mount,
              'device': mount.device,
              'fstype': mount.fstype,
              'size_total_gb': (mount.size_total / 1073741824) | round(2),
              'size_used_gb': (used / 1073741824) | round(2),
              'size_available_gb': (mount.size_available / 1073741824) | round(2),
              'used_percent': used_percent
            }) -%}
          {%- endfor -%}
          {{ result }}

    # ============================================
    # SECTION 3: NETWORK INFORMATION
    # ============================================
    - name: Collect network interfaces
      set_fact:
        network_interfaces: >-
          {%- set result = [] -%}
          {%- for interface in ansible_interfaces -%}
            {%- set iface = hostvars[inventory_hostname]['ansible_' + interface] | default({}) -%}
            {%- if iface.ipv4 is defined -%}
              {%- set _ = result.append({
                'interface': interface,
                'ipv4_address': iface.ipv4.address | default('N/A'),
                'ipv4_netmask': iface.ipv4.netmask | default('N/A'),
                'macaddress': iface.macaddress | default('N/A'),
                'mtu': iface.mtu | default('N/A'),
                'type': iface.type | default('N/A'),
                'active': iface.active | default(false)
              }) -%}
            {%- endif -%}
          {%- endfor -%}
          {{ result }}

    - name: Get default gateway
      set_fact:
        default_gateway: "{{ ansible_default_ipv4.gateway | default('N/A') }}"
        default_interface: "{{ ansible_default_ipv4.interface | default('N/A') }}"
        default_ip: "{{ ansible_default_ipv4.address | default('N/A') }}"

    - name: Get DNS servers
      shell: cat /etc/resolv.conf | grep nameserver | awk '{print $2}'
      register: dns_servers
      changed_when: false
      failed_when: false

    # ============================================
    # SECTION 4: INSTALLED PACKAGES
    # ============================================
    - name: Get installed packages (RHEL/CentOS)
      shell: rpm -qa --queryformat '%{NAME}|%{VERSION}|%{RELEASE}|%{INSTALLTIME:date}\n' | sort
      register: rpm_packages
      when: ansible_os_family == "RedHat"
      changed_when: false
      failed_when: false

    - name: Get installed packages (Debian/Ubuntu)
      shell: dpkg-query -W -f='${Package}|${Version}|${Status}\n' | grep "install ok installed" | cut -d'|' -f1,2
      register: deb_packages
      when: ansible_os_family == "Debian"
      changed_when: false
      failed_when: false

    - name: Count installed packages
      set_fact:
        package_count: "{{ rpm_packages.stdout_lines | length if ansible_os_family == 'RedHat' else deb_packages.stdout_lines | length }}"

    # ============================================
    # SECTION 5: RUNNING SERVICES
    # ============================================
    - name: Get running services (systemd)
      shell: systemctl list-units --type=service --state=running --no-pager --no-legend | awk '{print $1}'
      register: running_services
      changed_when: false
      failed_when: false

    - name: Get enabled services (systemd)
      shell: systemctl list-unit-files --type=service --state=enabled --no-pager --no-legend | awk '{print $1}'
      register: enabled_services
      changed_when: false
      failed_when: false

    # ============================================
    # SECTION 6: USER & GROUP INFORMATION
    # ============================================
    - name: Get local users
      shell: |
        awk -F: '$3 >= 1000 && $3 < 65534 {print $1"|"$3"|"$6"|"$7}' /etc/passwd
      register: local_users
      changed_when: false

    - name: Get users with sudo access
      shell: |
        getent group sudo wheel 2>/dev/null | cut -d: -f4 | tr ',' '\n' | sort -u
      register: sudo_users
      changed_when: false
      failed_when: false

    - name: Get last login information
      shell: lastlog -t 90 2>/dev/null | tail -n +2 | awk '{print $1"|"$4" "$5" "$6" "$7" "$8" "$9}'
      register: last_logins
      changed_when: false
      failed_when: false

    # ============================================
    # SECTION 7: SECURITY INFORMATION
    # ============================================
    - name: Check SELinux status (RHEL/CentOS)
      shell: getenforce 2>/dev/null || echo "Not Installed"
      register: selinux_status
      changed_when: false
      failed_when: false
      when: ansible_os_family == "RedHat"

    - name: Check AppArmor status (Debian/Ubuntu)
      shell: aa-status --enabled 2>/dev/null && echo "Enabled" || echo "Disabled/Not Installed"
      register: apparmor_status
      changed_when: false
      failed_when: false
      when: ansible_os_family == "Debian"

    - name: Check firewall status (firewalld)
      shell: systemctl is-active firewalld 2>/dev/null || echo "inactive"
      register: firewalld_status
      changed_when: false
      failed_when: false

    - name: Check firewall status (ufw)
      shell: ufw status 2>/dev/null | head -1 || echo "Not Installed"
      register: ufw_status
      changed_when: false
      failed_when: false

    - name: Check firewall status (iptables)
      shell: iptables -L -n 2>/dev/null | wc -l
      register: iptables_rules
      changed_when: false
      failed_when: false

    - name: Get listening ports
      shell: ss -tulnp 2>/dev/null | grep LISTEN | awk '{print $1"|"$5"|"$7}' | head -50
      register: listening_ports
      changed_when: false
      failed_when: false

    - name: Check SSH configuration
      shell: |
        echo "PermitRootLogin: $(grep -E '^PermitRootLogin' /etc/ssh/sshd_config 2>/dev/null | awk '{print $2}' || echo 'default')"
        echo "PasswordAuthentication: $(grep -E '^PasswordAuthentication' /etc/ssh/sshd_config 2>/dev/null | awk '{print $2}' || echo 'default')"
        echo "PubkeyAuthentication: $(grep -E '^PubkeyAuthentication' /etc/ssh/sshd_config 2>/dev/null | awk '{print $2}' || echo 'default')"
      register: ssh_config
      changed_when: false
      failed_when: false

    # ============================================
    # SECTION 8: SYSTEM STATUS
    # ============================================
    - name: Get system uptime
      shell: uptime -p 2>/dev/null || uptime
      register: system_uptime
      changed_when: false

    - name: Get load average
      set_fact:
        load_average: "{{ ansible_loadavg }}"

    - name: Check if reboot required (Debian/Ubuntu)
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file
      when: ansible_os_family == "Debian"

    - name: Check if reboot required (RHEL/CentOS)
      shell: needs-restarting -r 2>/dev/null; echo $?
      register: reboot_required_rhel
      changed_when: false
      failed_when: false
      when: ansible_os_family == "RedHat"

    # ============================================
    # SECTION 9: COMPILE REPORT
    # ============================================
    - name: Compile full asset inventory
      set_fact:
        asset_inventory:
          collection_date: "{{ ansible_date_time.iso8601 }}"
          system: "{{ system_info }}"
          hardware:
            cpu: "{{ cpu_info }}"
            memory: "{{ memory_info }}"
            disks: "{{ disk_details }}"
          network:
            default_ip: "{{ default_ip }}"
            default_gateway: "{{ default_gateway }}"
            default_interface: "{{ default_interface }}"
            dns_servers: "{{ dns_servers.stdout_lines | default([]) }}"
            interfaces: "{{ network_interfaces }}"
          software:
            package_count: "{{ package_count }}"
            running_services_count: "{{ running_services.stdout_lines | length }}"
            enabled_services_count: "{{ enabled_services.stdout_lines | length }}"
          users:
            local_users: "{{ local_users.stdout_lines | default([]) }}"
            sudo_users: "{{ sudo_users.stdout_lines | default([]) }}"
          security:
            selinux: "{{ selinux_status.stdout | default('N/A') }}"
            apparmor: "{{ apparmor_status.stdout | default('N/A') }}"
            firewalld: "{{ firewalld_status.stdout | default('N/A') }}"
            ufw: "{{ ufw_status.stdout | default('N/A') }}"
            iptables_rules_count: "{{ iptables_rules.stdout | default('0') }}"
            listening_ports: "{{ listening_ports.stdout_lines | default([]) }}"
            ssh_config: "{{ ssh_config.stdout_lines | default([]) }}"
          status:
            uptime: "{{ system_uptime.stdout }}"
            load_average: "{{ load_average }}"
            reboot_required: "{{ reboot_required_file.stat.exists | default(false) if ansible_os_family == 'Debian' else (reboot_required_rhel.rc | default(0) == 1) }}"

    # ============================================
    # SECTION 10: GENERATE REPORTS
    # ============================================
    - name: Display asset inventory summary
      debug:
        msg: |
          ================================================================================
          ASSET INVENTORY REPORT - {{ ansible_hostname }}
          Collection Date: {{ ansible_date_time.iso8601 }}
          ================================================================================
          
          SYSTEM INFORMATION
          ------------------
          Hostname:        {{ system_info.hostname }}
          FQDN:            {{ system_info.fqdn }}
          OS:              {{ system_info.distribution }} {{ system_info.distribution_version }}
          Kernel:          {{ system_info.kernel }}
          Architecture:    {{ system_info.architecture }}
          Virtualization:  {{ system_info.virtualization_type }}
          Serial:          {{ system_info.product_serial }}
          
          HARDWARE
          --------
          CPU:             {{ cpu_info.processor }}
          CPU Cores:       {{ cpu_info.processor_cores }} cores x {{ cpu_info.processor_count }} sockets
          vCPUs:           {{ cpu_info.processor_vcpus }}
          Memory Total:    {{ memory_info.memtotal_mb }} MB
          Memory Used:     {{ memory_info.memory_used_mb }} MB ({{ memory_info.memory_used_percent }}%)
          Swap Total:      {{ memory_info.swaptotal_mb }} MB
          
          NETWORK
          -------
          Primary IP:      {{ default_ip }}
          Gateway:         {{ default_gateway }}
          Interface:       {{ default_interface }}
          DNS Servers:     {{ dns_servers.stdout_lines | default([]) | join(', ') }}
          
          SOFTWARE
          --------
          Packages:        {{ package_count }} installed
          Running Svcs:    {{ running_services.stdout_lines | length }}
          Enabled Svcs:    {{ enabled_services.stdout_lines | length }}
          
          SECURITY
          --------
          SELinux:         {{ selinux_status.stdout | default('N/A') }}
          AppArmor:        {{ apparmor_status.stdout | default('N/A') }}
          Firewalld:       {{ firewalld_status.stdout | default('N/A') }}
          UFW:             {{ ufw_status.stdout | default('N/A') }}
          Open Ports:      {{ listening_ports.stdout_lines | length }}
          
          STATUS
          ------
          Uptime:          {{ system_uptime.stdout }}
          Load Average:    {{ load_average['1m'] }}, {{ load_average['5m'] }}, {{ load_average['15m'] }}
          Reboot Required: {{ 'Yes' if (reboot_required_file.stat.exists | default(false) if ansible_os_family == 'Debian' else (reboot_required_rhel.rc | default(0) == 1)) else 'No' }}
          ================================================================================

    - name: Save JSON report per host
      copy:
        content: "{{ asset_inventory | to_nice_json }}"
        dest: "{{ report_dir }}/{{ ansible_hostname }}_inventory.json"
      delegate_to: localhost
      become: no

    - name: Save CSV summary
      lineinfile:
        path: "{{ report_dir }}/inventory_summary.csv"
        line: "{{ ansible_hostname }},{{ default_ip }},{{ system_info.distribution }},{{ system_info.distribution_version }},{{ cpu_info.processor_vcpus }},{{ memory_info.memtotal_mb }},{{ package_count }},{{ running_services.stdout_lines | length }},{{ selinux_status.stdout | default('N/A') }},{{ firewalld_status.stdout | default('N/A') }},{{ system_uptime.stdout }}"
        create: yes
      delegate_to: localhost
      become: no

    - name: Add CSV header
      lineinfile:
        path: "{{ report_dir }}/inventory_summary.csv"
        line: "Hostname,IP,OS,Version,vCPUs,Memory_MB,Packages,Running_Services,SELinux,Firewall,Uptime"
        insertbefore: BOF
      delegate_to: localhost
      run_once: true
      become: no
