# Sample Inventory File for Asset Collection
# File: inventory/hosts.yml

all:
  children:
    linux_servers:
      children:
        webservers:
          hosts:
            web01:
              ansible_host: 192.168.1.10
            web02:
              ansible_host: 192.168.1.11
        
        dbservers:
          hosts:
            db01:
              ansible_host: 192.168.1.20
            db02:
              ansible_host: 192.168.1.21
        
        appservers:
          hosts:
            app01:
              ansible_host: 192.168.1.30
            app02:
              ansible_host: 192.168.1.31

  vars:
    ansible_user: ansible
    ansible_become: yes
    ansible_python_interpreter: /usr/bin/python3
